version: "3.8"

services:
  web:
    container_name: postman-api
    image: postman-api-drf:latest
    build: .
    # depends_on:
    #   - db
    ports:
      - "8000:8000"
    env_file:
      - .env  
    volumes:  # Comment/Remove this in production
      - .:/app

  
  db:
    container_name: postman-db
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  

    